baseURL = "https://vani2.github.io/"
publishDir = "docs"
disablePathToLower = true
languageCode = "en-us"
title = "Ivan Vavilov's blog"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
  mode = "auto"
  featherIconsCDN = true
  subtitle = "I'm Ivan. I write here about iOS, Swift and soft skills."
[markup.highlight]
  style = "dracula"

# Social

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/vani2/"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/vani297520105/"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/vavilovvani2/"

[[params.social]]
  name = "Facebook"
  icon = "facebook"
  url = "https://www.facebook.com/ivan.vavilov.90/"

[[params.social]]
  name = "Stack Overflow"
  icon = "code"
  url = "https://stackoverflow.com/users/1758448/ivan-vavilov"

# Main menu Items

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3
